# Site settings
title: More&More
email: moreandmoreunlimited@gmail.com
url: https://samatt.github.io/mmnew/
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-light: '#FFFFF'
  links: '#219ab3'

# Footer settings
footer: More&More

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MoreAndMoreLtd
  - title: instagram
    url: http://instagram.com/moreandmoreunlimited
  - title: tumblr
    url: http://moreandmoreunlimited.tumblr.com

# Build settings
markdown: kramdown
permalink: pretty
